# -*- coding: utf-8 -*-
"""Unemp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyaiLxLQc6VRNin9o1xbo0SE7S4YR7R7
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

path = '/content/Unemployment in India.csv'
df = pd.read_csv(path)

print("First five rows of dataset:")
print(df.head())
print("\nDataset Info:")
print(df.info())
print("\nMissing Values:\n", df.isnull().sum())


df.columns = df.columns.str.strip().str.replace(' ', '_')

print("\nStatistical Summary:")
print(df.describe())


plt.figure(figsize=(10,6))
sns.barplot(x='Region', y='Estimated_Unemployment_Rate_(%)', data=df, errorbar=None)
plt.xticks(rotation=90)
plt.title('Unemployment Rate by Region')
plt.xlabel('Region')
plt.ylabel('Estimated Unemployment Rate (%)')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))
sns.lineplot(x='Date', y='Estimated_Unemployment_Rate_(%)', data=df)
plt.title('Month-wise Unemployment Trend')
plt.xlabel('Date')
plt.ylabel('Unemployment Rate (%)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))
sns.scatterplot(x='Estimated_Employed', y='Estimated_Labour_Participation_Rate_(%)', data=df)
plt.title('Employment vs Labour Participation')
plt.xlabel('Estimated Employed')
plt.ylabel('Labour Participation Rate')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()


print("\n🔍 Insights:")
print("- Unemployment rates vary widely across regions.")
print("- Certain months show spikes in unemployment (e.g., during lockdown).")
print("- Employment and labour participation are positively correlated.")